// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf_g4qK6Yotzx62HRL0TwcGMVPTkLzNTs',
    appId: '1:845203405278:web:716f96a6917863693c054f',
    messagingSenderId: '845203405278',
    projectId: 'barca-store-final-2026',
    authDomain: 'barca-store-final-2026.firebaseapp.com',
    storageBucket: 'barca-store-final-2026.firebasestorage.app',
    measurementId: 'G-8XBC24GHBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtpMpDcHO5k-fAVDjE-ZsN-OU3M7t2LA',
    appId: '1:845203405278:android:4a0908ca13b9b8e53c054f',
    messagingSenderId: '845203405278',
    projectId: 'barca-store-final-2026',
    storageBucket: 'barca-store-final-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9QJlBXwD4JHNXrDxIJED0gyEpr2yVfaM',
    appId: '1:845203405278:ios:3c51f20007df1f3a3c054f',
    messagingSenderId: '845203405278',
    projectId: 'barca-store-final-2026',
    storageBucket: 'barca-store-final-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9QJlBXwD4JHNXrDxIJED0gyEpr2yVfaM',
    appId: '1:845203405278:ios:3c51f20007df1f3a3c054f',
    messagingSenderId: '845203405278',
    projectId: 'barca-store-final-2026',
    storageBucket: 'barca-store-final-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf_g4qK6Yotzx62HRL0TwcGMVPTkLzNTs',
    appId: '1:845203405278:web:c0c58347cc787e2a3c054f',
    messagingSenderId: '845203405278',
    projectId: 'barca-store-final-2026',
    authDomain: 'barca-store-final-2026.firebaseapp.com',
    storageBucket: 'barca-store-final-2026.firebasestorage.app',
    measurementId: 'G-795BVYET7M',
  );
}
